apiVersion: v1
kind: Secret
metadata:
  name: wow-auth-secret
  namespace: wow-checklists
type: Opaque
data:
  sessionSecret: c3VwZXItc2VjcmV0LWNoYW5nZS1tZQ==
  bnetClientId: ZHVtbXktY2xpZW50LWlk
  bnetClientSecret: ZHVtbXktY2xpZW50LXNlY3JldA==
  cifsUsername: bmFzLXVzZXI=
  cifsPassword: bmFzLXBhc3N3b3Jk
